version: '3.8'

services:
  web-app:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: lab-web
    secrets:
      - db_password
    networks:
      - backend
    depends_on:
      - db
  db:
    build:
      context: ./db
      dockerfile: Dockerfile
    container_name: lab-db
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
    secrets:
      - db_password
    networks:
      - backend
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: lab-server
    ports:
      - "8000:80"
    networks:
      - backend
    depends_on:
      - web-app
secrets:
  db_password:
    file: ./db_password.txt
networks:
  backend:
